# Generated by Django 4.1.9 on 2023-06-14 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('join_date', models.DateField()),
                ('sal', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dept')),
            ],
        ),
    ]
